name: Get Weather


on:
  schedule:
    - cron: '30 8 * * *'  # This means 08:30 every day
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run weather automation script
        run: |
          python weather_automation.py

      - name: Push changes
        run: |
          git config --global user.email "gracemurphy45@gmail.com"  # Replace with your email
          git config --global user.name "GraceMarySmyth"  # Replace with your name
          git add .
          git commit -m "Update from weather automation"
          git push
